In [25]:
import pandas as pd

# Raw US House election data
raw_df = pd.read_csv('data/rep.csv', sep='\t', header=None, names=['raw_text'])

# Separate data into columns and filter for 2024 results only
clean_df = raw_df['raw_text'].str.split(',', expand=True)
header = clean_df.iloc[0]

data_rows = clean_df.iloc[1:]
df_2024 = data_rows[data_rows[0] == '2024']

# Clean data length
df_2024 = df_2024.iloc[:, :len(header)]
df_2024.columns = header
df_2024 = df_2024.iloc[:, :-2]

df_2024.to_csv('data/rep_2024.csv', index=False)
df_2024.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,fusion_ticket
32453,2024,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,FALSE,FALSE,BARRY MOORE,REPUBLICAN,FALSE,TOTAL,258619,329854,FALSE,20250910,FALSE
32454,2024,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,FALSE,FALSE,TOM HOLMES,DEMOCRAT,FALSE,TOTAL,70929,329854,FALSE,20250910,FALSE
32455,2024,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,FALSE,FALSE,WRITEIN,NA,TRUE,TOTAL,306,329854,FALSE,20250910,FALSE
32456,2024,ALABAMA,AL,1,63,41,US HOUSE,2,GEN,FALSE,FALSE,CAROLEENE DOBSON,REPUBLICAN,FALSE,TOTAL,131414,289674,FALSE,20250910,FALSE
32457,2024,ALABAMA,AL,1,63,41,US HOUSE,2,GEN,FALSE,FALSE,SHOMARI FIGURES,DEMOCRAT,FALSE,TOTAL,158041,289674,FALSE,20250910,FALSE

In [26]:
df = pd.read_csv('data/rep_2024.csv')

# Reset index
df.reset_index(drop=True, inplace=True)

# Convert column B to string, pad it to 2 digits, and combine with column A
df['district'] = df['state_po'] + df['district'].astype(str).str.zfill(2)

# Drop unnecessary data
columns_to_drop = ['state_fips', 'state_cen', 'state_ic', 'state_po', 'office', 'writein', 'mode', 'unofficial', 'version', 'fusion_ticket']
df = df.drop(columns=columns_to_drop)

# Capitalize columns
df.columns = df.columns.str.capitalize()

df_2024.to_csv('data/rep_2024.csv', index=False)
df.head()

,Year,State,District,Stage,Runoff,Special,Candidate,Party,Candidatevotes,Totalvotes
0,2024,ALABAMA,AL01,GEN,False,False,BARRY MOORE,REPUBLICAN,258619,329854
1,2024,ALABAMA,AL01,GEN,False,False,TOM HOLMES,DEMOCRAT,70929,329854
2,2024,ALABAMA,AL01,GEN,False,False,WRITEIN,NaN,306,329854
3,2024,ALABAMA,AL02,GEN,False,False,CAROLEENE DOBSON,REPUBLICAN,131414,289674
4,2024,ALABAMA,AL02,GEN,False,False,SHOMARI FIGURES,DEMOCRAT,158041,289674